"use client";
import { useEffect, useState } from "react";
import { Activity, Bot, CheckCircle2, ChevronLeft, ChevronRight, Command, Inbox, LayoutDashboard, ShieldCheck, Users, Zap } from "lucide-react";

type Approval = { id:string; description:string; task:{userInput:string}; autonomyLevel:string };
type Feed = { id:string; event:string; actor:string; timestamp:string; description:string };

export default function Home(){
 const [command,setCommand]=useState(""); const [result,setResult]=useState<any>(null); const [busy,setBusy]=useState(false); const [collapsed,setCollapsed]=useState(false); const [approvals,setApprovals]=useState<Approval[]>([]); const [feed,setFeed]=useState<Feed[]>([]);
 const refresh=async()=>{const [a,f]=await Promise.all([fetch("/api/approvals"),fetch("/api/activity")]); setApprovals(await a.json()); setFeed(await f.json());};
 useEffect(()=>{refresh()},[]);
 const execute=async()=>{if(!command.trim()||busy)return; setBusy(true); setResult(null); try{const r=await fetch("/api/command",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({input:command})}); setResult(await r.json()); setCommand(""); await refresh();}finally{setBusy(false)}};
 const approve=async(id:string,approved:boolean)=>{await fetch("/api/approvals",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({actionId:id,approved})}); await refresh(); setResult({status:approved?"approved":"rejected",message:approved?"Ação aprovada e executada no ambiente mock.":"Ação rejeitada."});};
 return <main className="shell">
  <aside className={collapsed?"sidebar collapsed":"sidebar"}><div className="brand"><div className="brandMark">W</div>{!collapsed&&<div><strong>PERSONAL AI</strong><span>WORKFORCE</span></div>}</div><nav><button className="navItem active"><LayoutDashboard size={18}/>{!collapsed&&<span>Command Center</span>}</button><button className="navItem"><Users size={18}/>{!collapsed&&<span>My Workforce</span>}</button><button className="navItem"><CheckCircle2 size={18}/>{!collapsed&&<span>Tasks</span>}</button><button className="navItem"><ShieldCheck size={18}/>{!collapsed&&<span>Approvals</span>}{!collapsed&&approvals.length>0&&<b>{approvals.length}</b>}</button><button className="navItem"><Activity size={18}/>{!collapsed&&<span>Activity</span>}</button></nav><div className="sidebarBottom"><button className="collapse" onClick={()=>setCollapsed(!collapsed)}>{collapsed?<ChevronRight size={18}/>:<><ChevronLeft size={18}/><span>Collapse</span></>}</button></div></aside>
  <section className="content"><header><div><div className="eyebrow">PERSONAL AI WORKFORCE · MVP</div><h1>Command Center</h1></div><div className="profile"><div className="online"/><div className="avatar">MH</div><div className="profileText"><strong>Mauricio</strong><span>Owner</span></div></div></header>
   <div className="commandBox"><Command size={20}/><input value={command} onChange={e=>setCommand(e.target.value)} onKeyDown={e=>e.key==="Enter"&&execute()} placeholder="Diga ao seu workforce o que precisa acontecer..."/><button onClick={execute} disabled={busy}><Zap size={16}/>{busy?"Running":"Execute"}</button></div>
   {result&&<div className="toast"><CheckCircle2 size={17}/><span><strong>{result.status}</strong> — {result.message}</span></div>}
   <div className="metrics"><Metric icon={<Users/>} label="Agents" value="1" sub="Mail & Calendar"/><Metric icon={<Inbox/>} label="Pending approvals" value={String(approvals.length)} sub="human decision required"/><Metric icon={<Activity/>} label="Audit events" value={String(feed.length)} sub="latest 50"/><Metric icon={<Bot/>} label="Runtime" value="ONLINE" sub="Next.js MVP"/></div>
   <div className="grid"><section className="panel workforce"><div className="panelHead"><div><span className="sectionLabel">WORKFORCE</span><h2>Active agent</h2></div></div><div className="agent"><div className="agentIcon purple"><Bot size={19}/></div><div className="agentMain"><div className="agentTitle"><strong>Mail</strong><span>Email & Calendar Operations</span></div><p>Specialized agent with mock email/calendar tools and hard policy gates.</p></div><div className="status working"><i/>Active</div></div></section>
    <section className="panel approvals"><div className="panelHead"><div><span className="sectionLabel">HUMAN GATE</span><h2>Approval queue</h2></div><span className="count">{approvals.length}</span></div>{approvals.length===0?<div className="empty">Nenhuma ação aguardando aprovação.</div>:approvals.map(a=><div className="approval" key={a.id}><ShieldCheck size={17}/><div><strong>{a.description}</strong><small>{a.autonomyLevel} · {a.task.userInput}</small></div><button onClick={()=>approve(a.id,true)}>Approve</button><button onClick={()=>approve(a.id,false)}>Reject</button></div>)}</section></div>
   <section className="panel activity"><div className="panelHead"><div><span className="sectionLabel">AUDIT STREAM</span><h2>Workforce activity</h2></div><Activity size={18}/></div>{feed.length===0?<div className="empty">Nenhum evento ainda. Execute um comando.</div>:feed.map(x=><div className="feed" key={x.id}><span className="feedDot"/><div><strong>{x.description}</strong><small>{x.actor} · {new Date(x.timestamp).toLocaleString("pt-PT")}</small></div></div>)}</section>
  </section></main>
}
function Metric({icon,label,value,sub}:{icon:React.ReactNode;label:string;value:string;sub:string}){return <div className="metric"><div className="metricIcon">{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{sub}</small></div></div>}
